baseURL: 'https://atbreuer11.github.io'
languageCode: en-us
title: atbreuer11.github.io
theme: toha
googleAnalytics: G-VFP107V0DB

enableEmoji: true

languages:
  en:
    languageName: English
    weight: 1

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

params:
  gitRepo: 'https://github.com/atbreuer11/atbreuer11.github.io'
  gitBranch: main
  enableTOC: true
  background: images/hero.png
  logo:
    main: images/logo.png
    inverted: images/logo.png
    # favicon: /images/site/favicon.png
  newsletter:
    enable: false
