baseURL: 'https://atbreuer11.github.io'
languageCode: en-us
title: My Portfolio
theme: toha

enableEmoji: true

languages:
  en:
    languageName: English
    weight: 1

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

params:
  gitRepo: 'https://github.com/atbreuer11/atbreuer11.github.io'
  gitBranch: master
  enableTOC: true
  background: images/haleakala.png
